
import type { Metadata } from "next";
import "./globals.css";
import { NextUIProvider } from "@nextui-org/react";
export const metadata: Metadata = {
  title: "Create Next App111",
  description: "Generated by create next app",
};

import { Poppins } from 'next/font/google'
import { Tiro_Tamil } from 'next/font/google'
import { Roboto } from 'next/font/google'

const popin = Poppins( {
  weight: [ '100', '200', '300', '400', '500', '600', '700', '800', '900' ],
  subsets: [ "latin" ],
  variable: '--font-poppin'
} );
const tiro_timil = Tiro_Tamil( {
  weight: [ '400' ],
  subsets: [ "latin" ],
  variable: '--Tiro-Tamil'
} );
const roboto = Roboto( {
  weight: [ '400', '900' ],
  subsets: [ "latin" ],
  variable: '--font-Roboto'
} );
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={ `${ popin.variable } ${ tiro_timil.variable } ${ roboto.variable }` }>
        {children}
      </body>
    </html>
  );
}
